// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiwuapjkgsusstdzgdnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pd3VhcGprZ3N1c3N0ZHpnZG5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDMxODIsImV4cCI6MjA2MjYxOTE4Mn0.grp9ojvgehj6HSDyoLMx4aD02DZ8WDpaCrD2rdPGRUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);